### ISSUE TITLE
Spawn.spawning.setDirections() unable to change number of directions

### ISSUE THREAD

**Issue by laverdet** [screeps/engine#108]
I'm having an issue with the setDirections API call. It won't let me decrease the number of directions supplied. For instance if I create a creep via: `spawn.spawnCreep(body, name, { directions: [ TOP, BOTTOM ] });` and then later I perform `spawn.spawning.setDirections([ LEFT ]);` then the directions that actually get set are: `[ LEFT, BOTTOM ]`. It seems like it's merging the old directions and the new ones instead of just overwriting as I would expect.

This is happening on a local server, I'm not sure if it happens on MMO as well.

cc: @sparr because you worked on this in #61

**Comment by ags131** [comment]
If it is in `bulk.update`, its likely this line
https://github.com/screeps/driver/blob/master/lib/bulk.js#L42

**Comment by sparr** [comment]
That seems like it. lodash merge won't delete keys that already exist but aren't in the replacement object. I've been away too long and forgotten the architecture here so I'm not sure of an appropriate fix.

**Comment by o4kapuk** [comment]
Thanks, I'll take a look

**Comment by sparr** [comment]
One fix at the outer level would be to change the spawn directions from a list of 0-8 numbers to an array of 8 true/false values.

**Comment by o4kapuk** [comment]
Should be [fixed](https://github.com/screeps/engine/commit/001ca6b0850b8f0ba5360339c4711297b4fb315a) currently.
