### ISSUE TITLE
Construction sites for roads on swamps are inconsistent

### ISSUE THREAD

**Issue by roncli** [screeps/engine#20]
http://screeps.com/s/hqxDDh

Note the road at 24,35, which was most recently placed and placed manually, requires 300 energy.  However, the road at 23,24, which was placed via script, requires 1500 energy.

I'm not sure exactly what's going on, but I was able to catch the inconsistency on replay.

Also, I wasn't sure which project to place this in, this one seemed most logical since the code to calculate it appears to be here.

**Comment by artch** [comment]
Please use our in-game ticket system when reporting issues in the game world (a menu option "Report a problem" or [this web form](http://support.screeps.com/hc/en-us/requests/new)). Alternatively, you can use our [forums](http://support.screeps.com/hc/en-us/community/topics/200280412-Technical-Issues-and-Bugs). GitHub Issues are mostly for bug reports regarding private server features.

We'll look into this road issue ASAP.
