### ISSUE TITLE
Limit LOC Based On GCL

### ISSUE THREAD

**Issue by tstivers1990** [screeps/engine#49]
As the title says, I think the total LOC of your scripts should be limited based on GCL. I'm sick of always having TooAngel or bonzAI as my neighbor, and it's bad for the game in general when open source scripts become rampant.

It sets the barrier too high for new players. This creates a scenario where in order to even survive early on, a new player needs to be able to match the open source AIs with 50k+ lines of code, when the new player barely even understands the basics of the API.

Players using an open source AI are theoretically likely to be more aggressive than players who had to write their own AI, as they don't have any appreciation of the effort it takes to write an AI that is capable of defending rooms, attacking other players, etc, all without crashing the economy. This amplifies the above issue.

Players using an open source AI aren't likely to stick around long. The whole point of the game is programming. Take that away, and what is left? If these are Steam players, then each one will be wasting up to 10 cpu/tick for quite a while until someone decides to wipe them out. Where a player who wrote his own AI and got bored would likely be using up much less cpu/tick, as their AI will be much less robust. This also feeds into the first issue by pushing other new players into having to use an open source AI to even survive.

Your target audience, I would imagine, are programmers. People who can actually write code. Not people who can copy/paste code. I myself am a programmer, and I would much rather write my own AI than use one of the open source AIs. However, on shard1, in the initial green zone I spawned in, there was a TooAngel bot who was about on pace with me. And the only reason it wasn't well ahead of me is a combination of where I spawned giving me a choke point and the fact I reserved any rooms he would have been able to expand to before he could expand, forcing him to respawn.

After hitting GCL 3 I decided to move to a blue zone before I hit GCL 4 so that I would be able to claim a new room once I hit GCL 4. Upon doing this, I was wiped out over night by someone using the standard bonzAI layout. The place I had chosen wasn't overly close to anyone as far as I could tell, and I hadn't been aggressive towards that player. This isn't a positive new player experience. If it was bonzAI himself, that would be one thing. But when it's someone else using the bonzAI source he copy/pasted from github, that leaves a pretty sour taste in your mouth. That taste could only be more sour if that someone purchased the bonzAI source from Screeps with real currency.

Limiting the maximum lines of code per repo based on the player's GCL would go a long way towards resolving this. It could be done in a way that discourages the use of full-fledged open source AIs, but doesn't hinder the player's ability to advance. The open source AIs are in the 10s of thousands of lines of code, where a player under GCL 5 isn't likely to have more than 10,000 lines of code.

Ideally, the limit would only be for the first 10 levels, and then it gets lifted so that the player's maximum is unchanged from what it is today. The limit would also ideally have enough room after the first couple levels of GCL that the player could use third party libraries such as behavior3 or Traveler without reaching their LOC cap.

Obviously this could be circumvented by separating the code for the open source AIs out into stages that could be used at each GCL, and it won't stop the truly determined from copy/pasting an open source AI. But to separate out the open source AIs into stages would be quite an undertaking, and I doubt anyone in the community would be willing to do this just for the sake of being able to use the AI before GCL 10. Thus, it would still serve its purpose of preventing new players from copy/pasting an open source AI.

Over all, I think this change will go a long way towards improving this game. If it's not this change that solves the problem, then I think something else definitely needs to be done to solve the problem. As it is currently, it's just TooAngel vs bonzAI, and that's no fun.

**Comment by DanielVF** [comment]
A lines of code count check would be completely foiled by removing the new lines from a codebase with a minimizer. :)

That said, both TooAngel and bonAI don't attack out of the box, correct? So you are playing against someone who is writing their own code.

I think the "actual" problem is that in screeps you sometimes have to respawn several times before you get a spot you can live in. Loosing all your rooms when you respawn, and then loosing your new rooms to somebody at your new place feels disheartening.

In reality, you keep your GCL, and you keep your code. You are actually stronger on each respawn, it just doesn't feel that way.

The trick is making this process feel newbie friendly - or maybe at least warn new players that Green zones are the great blood areas, Blue zones are almost as bad, and you may need to respawn a few times.

**Comment by artch** [comment]
Please use [our forum](https://screeps.com/forum) to post feature requests. This issue tracker is for engine bugs and technical issues.
