### ISSUE TITLE
NPM version broken [2.9.0]

### ISSUE THREAD

**Issue by ags131** [screeps/engine#51]
It looks like the NPM version did not get built before publishing, this results in the `bin` files not being symlinked and `dist` folder not existing.

**Comment by artch** [comment]
I've just made a fresh install, and it looks fine. Could you please provide more info on how to reproduce it?

**Comment by ags131** [comment]
Just did an install in an empty folder and it installed fine, went back to the live folder and it still failed, after removing node_modules and any .lock files it now installs fine, sorry for the trouble.
