### ISSUE TITLE
spawnCreep should automatically assign a name

### ISSUE THREAD

**Issue by NobodysNightmare** [screeps/engine#55]
I just noticed that `spawnCreep` (as opposed to `createCreep`) does not automatically assign a name to created creeps anymore.

I think this is an unneccessary complication for new players, which should not use a deprecated method like `createCreep`, should they?

Was there a particular reason to leave that behaviour out? The pull request does not at all mention this change, I discovered it by chance after seeing that my spawning code does not work after changing to the new method signature.

edit: In case you want to keep the behaviour as is, the documentation of return values should be updated. Currently it only points at an errorneous creep body, but not at a missing name.

**Comment by Angoulor** [comment]
I agree with this. Even though there's a limited number of names, and problems with scalability, I feel like new players will prefer to create a naming function later. They won't really care for their creeps' names right at the beginning.

**Comment by artch** [comment]
Please create new issues only for bug reports and other technical issues. Your discussion is more appropriate to the [original PR thread](https://github.com/screeps/engine/pull/38).

**Comment by artch** [comment]
Please create new issues only for bug reports and other technical issues. Your discussion is more appropriate to the [original PR thread](https://github.com/screeps/engine/pull/38) or [forum post thread](https://screeps.com/forum/topic/1951/changelog-2017-09-28).
