### ISSUE TITLE
Destroying lab does not drop minerals

### ISSUE THREAD

**Issue by creidieki** [screeps/engine#60]
Destroying a lab doesn't drop any minerals that were inside on the ground. I think the problem is that  engine/src/processor/intents/room/destroy-structure.js   is only checking object[resourceType] (which is the equivalent of .store? I think?)

This may also affect nukers full of ghodium; I'm not quite dedicated enough to bug reporting to test that one.

**Comment by sparr** [comment]
The source here is tricky. Apparently the "type" of all ground resources is "energy" and there's a separate resourceType? I can't quite follow the logic in destroy-structure and _create-energy

**Comment by Creosteanu** [comment]
Looks done. @artch could be closed?

**Comment by o4kapuk** [comment]
Fixed
