### ISSUE TITLE
Feature request: cancel spawning

### ISSUE THREAD

**Issue by sparr** [screeps/engine#64]
artch brought this up in #61 where StructureSpawn.spawning is growing up to have a prototype instead of just being a bare object. Once we have `StructureSpawn.Spawning.setDirections()` there's nothing technically stopping us from having `.cancel()`.

Some folks discussed this in #general on Slack and I want to get feedback here on how spawn canceling should work.

Should you be able to use it at any time?
Should you get a refund on the energy you spent? (yes, no, partial)
Where should that refund go? (back to extensions, dropped on spawn, dropped/stored adjacent to spawn, ...)
Should you be able to start a new spawncreep on the same tick as canceling a current one?

**Comment by artch** [comment]
> Should you be able to use it at any time?

Yes, why not?

> Should you get a refund on the energy you spent?

I'd say no.

> Should you be able to start a new spawncreep on the same tick as canceling a current one?

No, it would complicate things a lot without any real benefit.
