### ISSUE TITLE
Request: Remove minimum resource amount for StructureTerminal.send()

### ISSUE THREAD

**Issue by jim-hart** [screeps/engine#78]
While its not a huge problem, being unable to send a resources in amounts of less than 100 can be a hassle.  With multiple rooms producing multiple resources, its easy to accumulate small amounts of intermediary products.  The same is true for minerals used to boost creeps; its easy to exhaust your supply of a certain boost, but still have around 10-20 minerals remaining.  

While a single room experiencing this issue can be easily rectified, as the number of owned rooms increases, it becomes less manageable.  Small resource pockets of a specific type scattered across enough rooms can add up to the hundreds, if not thousands.  As it stands, the only way to transfer resources in amounts of less than 100 through a terminal is by creating a buy order and having the target room purchase it (or just outright selling the resource to get rid of it).  

`.send()` already incurs the standard energy cost and cooldown, so I don't feel the 100 unit threshold should be added to that.  While not restricting market transactions to this threshold makes sense, its still worth pointing out you can buy and sell in 1 unit increments.  

While I don't foresee something like this being useful continuously, managing logistics would be more manageable if you didn't have to factor in resource counts when trying to consolidate a single resource type across multiple rooms.

**Comment by bastianh** [comment]
the bugtracker is not the place to discuss changes to the game .. you should post that in the forums: https://screeps.com/forum/

**Comment by jim-hart** [comment]
@bastianh I checked the issue tracker before submitting this; I saw similar posts; [like this](https://github.com/screeps/engine/issues/64) for example, and didn't see any complaints.  Would you still like me to close it?

**Comment by artch** [comment]
#64 was related to changes in a specific pull request here. General feature requests are better discussed on forums since they have more to do with the game itself rather than its open source engine.

**Comment by jim-hart** [comment]
@artch Its not a problem; I've already closed the issue.  I'll keep issues like this to the forums; take care.
